import * as React from "react";
import { DataGrid } from "@mui/x-data-grid";
import Paper from "@mui/material/Paper";

import { IconButton } from "@mui/material";

import CreateIcon from "@mui/icons-material/Create";
import DeleteIcon from "@mui/icons-material/Delete";

const columns = [
  { field: "id", headerName: "ID", width: 10 },
  { field: "dni", headerName: "DNI", width: 100 },
  { field: "nombre", headerName: "NOMBRE", width: 200 },
  { field: "apellido", headerName: "APELLIDO", width: 200 },
  { field: "genero", headerName: "GÉNERO", width: 100 },
  { field: "telefono", headerName: "TELÉFONO", width: 125 },
  { field: "direccion", headerName: "DIRECCIÓN", width: 250 },
  { field: "email", headerName: "EMAIL", width: 200 },
  { field: "ciudad", headerName: "CIUDAD", width: 150 },
  { field: "pais", headerName: "PAIS", width: 150 },

  {
    field: "actions",
    headerName: "ACCIÓN",
    width: 100,
    renderCell: (params) => (
      <>
        <IconButton onClick={() => handleEdit(params.row.id)}>
          <CreateIcon />
        </IconButton>
        <IconButton onClick={() => handleDelete(params.row.id)}>
          <DeleteIcon />
        </IconButton>
      </>
    ),
  },
];

const rows = [
  {
    id: 1,
    dni: "70321548",
    nombre: "Luis",
    apellido: "González",
    genero: "Masculino",
    telefono: "987654321",
    direccion: "Av. Arequipa 1234",
    email: "luis.gonzalez@gmail.com",
    ciudad: "Lima",
    pais: "Perú",
  },
  {
    id: 2,
    dni: "47896521",
    nombre: "María",
    apellido: "Fernández",
    genero: "Femenino",
    telefono: "965432187",
    direccion: "Calle Los Jardines 345",
    email: "maria.fernandez@hotmail.com",
    ciudad: "Trujillo",
    pais: "Perú",
  },
  {
    id: 3,
    dni: "85632147",
    nombre: "Juan",
    apellido: "Rojas",
    genero: "Masculino",
    telefono: "912345678",
    direccion: "Av. Larco 567",
    email: "juan.rojas@yahoo.com",
    ciudad: "Cusco",
    pais: "Perú",
  },
  {
    id: 4,
    dni: "63548971",
    nombre: "Ana",
    apellido: "Pérez",
    genero: "Femenino",
    telefono: "923456789",
    direccion: "Jr. Puno 890",
    email: "ana.perez@gmail.com",
    ciudad: "Arequipa",
    pais: "Perú",
  },
  {
    id: 5,
    dni: "75896324",
    nombre: "Carlos",
    apellido: "Ramírez",
    genero: "Masculino",
    telefono: "976543218",
    direccion: "Av. Javier Prado 120",
    email: "carlos.ramirez@gmail.com",
    ciudad: "Lima",
    pais: "Perú",
  },
  {
    id: 6,
    dni: "69857432",
    nombre: "Rosa",
    apellido: "Mendoza",
    genero: "Femenino",
    telefono: "983456712",
    direccion: "Calle Lima 342",
    email: "rosa.mendoza@hotmail.com",
    ciudad: "Piura",
    pais: "Perú",
  },
  {
    id: 7,
    dni: "25478963",
    nombre: "Pedro",
    apellido: "Vargas",
    genero: "Masculino",
    telefono: "911234567",
    direccion: "Av. Angamos 564",
    email: "pedro.vargas@yahoo.com",
    ciudad: "Chiclayo",
    pais: "Perú",
  },
  {
    id: 8,
    dni: "74589632",
    nombre: "Elena",
    apellido: "Castro",
    genero: "Femenino",
    telefono: "954321876",
    direccion: "Jr. Amazonas 678",
    email: "elena.castro@gmail.com",
    ciudad: "Iquitos",
    pais: "Perú",
  },
  {
    id: 9,
    dni: "89562341",
    nombre: "Diego",
    apellido: "Torres",
    genero: "Masculino",
    telefono: "921345678",
    direccion: "Calle Las Flores 120",
    email: "diego.torres@gmail.com",
    ciudad: "Tacna",
    pais: "Perú",
  },
  {
    id: 10,
    dni: "32165487",
    nombre: "Claudia",
    apellido: "Reyes",
    genero: "Femenino",
    telefono: "934567812",
    direccion: "Av. Pardo 432",
    email: "claudia.reyes@hotmail.com",
    ciudad: "Lima",
    pais: "Perú",
  },
  {
    id: 11,
    dni: "74123659",
    nombre: "Jorge",
    apellido: "Salazar",
    genero: "Masculino",
    telefono: "987654323",
    direccion: "Av. San Martín 987",
    email: "jorge.salazar@gmail.com",
    ciudad: "Huancayo",
    pais: "Perú",
  },
  {
    id: 12,
    dni: "85296341",
    nombre: "Mónica",
    apellido: "Peña",
    genero: "Femenino",
    telefono: "912345678",
    direccion: "Calle San Miguel 654",
    email: "monica.pena@yahoo.com",
    ciudad: "Lima",
    pais: "Perú",
  },
  {
    id: 13,
    dni: "65478921",
    nombre: "Miguel",
    apellido: "Silva",
    genero: "Masculino",
    telefono: "923456781",
    direccion: "Av. Grau 231",
    email: "miguel.silva@gmail.com",
    ciudad: "Cusco",
    pais: "Perú",
  },
  {
    id: 14,
    dni: "98751234",
    nombre: "Laura",
    apellido: "Gutiérrez",
    genero: "Femenino",
    telefono: "956123478",
    direccion: "Jr. Libertad 234",
    email: "laura.gutierrez@hotmail.com",
    ciudad: "Lima",
    pais: "Perú",
  },
  {
    id: 15,
    dni: "32187456",
    nombre: "Ricardo",
    apellido: "Lopez",
    genero: "Masculino",
    telefono: "934567813",
    direccion: "Calle Los Olivos 876",
    email: "ricardo.lopez@gmail.com",
    ciudad: "Arequipa",
    pais: "Perú",
  },
  {
    id: 16,
    dni: "65412387",
    nombre: "Patricia",
    apellido: "Martínez",
    genero: "Femenino",
    telefono: "912345678",
    direccion: "Av. Universitaria 543",
    email: "patricia.martinez@yahoo.com",
    ciudad: "Lima",
    pais: "Perú",
  },
  {
    id: 17,
    dni: "12365487",
    nombre: "Felipe",
    apellido: "Vega",
    genero: "Masculino",
    telefono: "976543219",
    direccion: "Jr. Bolívar 987",
    email: "felipe.vega@gmail.com",
    ciudad: "Piura",
    pais: "Perú",
  },
  {
    id: 18,
    dni: "47852316",
    nombre: "Verónica",
    apellido: "Romero",
    genero: "Femenino",
    telefono: "983456712",
    direccion: "Calle Olavide 678",
    email: "veronica.romero@hotmail.com",
    ciudad: "Lima",
    pais: "Perú",
  },
  {
    id: 19,
    dni: "85214796",
    nombre: "Hugo",
    apellido: "Ortiz",
    genero: "Masculino",
    telefono: "911234567",
    direccion: "Av. España 120",
    email: "hugo.ortiz@yahoo.com",
    ciudad: "Chiclayo",
    pais: "Perú",
  },
  {
    id: 20,
    dni: "47852369",
    nombre: "Gabriela",
    apellido: "Muñoz",
    genero: "Femenino",
    telefono: "954321876",
    direccion: "Jr. Las Palmeras 987",
    email: "gabriela.munoz@gmail.com",
    ciudad: "Iquitos",
    pais: "Perú",
  },
  {
    id: 21,
    dni: "96547812",
    nombre: "Andrés",
    apellido: "Paredes",
    genero: "Masculino",
    telefono: "921345678",
    direccion: "Av. Arenales 432",
    email: "andres.paredes@gmail.com",
    ciudad: "Lima",
    pais: "Perú",
  },
  {
    id: 22,
    dni: "32547896",
    nombre: "Sofía",
    apellido: "Navarro",
    genero: "Femenino",
    telefono: "934567812",
    direccion: "Av. Perú 876",
    email: "sofia.navarro@hotmail.com",
    ciudad: "Cusco",
    pais: "Perú",
  },
  {
    id: 23,
    dni: "47852314",
    nombre: "Mauricio",
    apellido: "Espinoza",
    genero: "Masculino",
    telefono: "987654321",
    direccion: "Jr. Gamarra 120",
    email: "mauricio.espinoza@gmail.com",
    ciudad: "Huancayo",
    pais: "Perú",
  },
  {
    id: 24,
    dni: "12387456",
    nombre: "Clara",
    apellido: "Rojas",
    genero: "Femenino",
    telefono: "965432187",
    direccion: "Calle Las Gardenias 123",
    email: "clara.rojas@yahoo.com",
    ciudad: "Lima",
    pais: "Perú",
  },
  {
    id: 25,
    dni: "36547891",
    nombre: "Emilio",
    apellido: "Zapata",
    genero: "Masculino",
    telefono: "912345678",
    direccion: "Av. Abancay 765",
    email: "emilio.zapata@gmail.com",
    ciudad: "Lima",
    pais: "Perú",
  },
  {
    id: 26,
    dni: "65412398",
    nombre: "Lucía",
    apellido: "Montalvo",
    genero: "Femenino",
    telefono: "923456789",
    direccion: "Jr. Tacna 654",
    email: "lucia.montalvo@hotmail.com",
    ciudad: "Trujillo",
    pais: "Perú",
  },
  {
    id: 27,
    dni: "96587412",
    nombre: "Francisco",
    apellido: "Cabrera",
    genero: "Masculino",
    telefono: "976543219",
    direccion: "Av. Los Próceres 123",
    email: "francisco.cabrera@gmail.com",
    ciudad: "Piura",
    pais: "Perú",
  },
  {
    id: 28,
    dni: "45698732",
    nombre: "Natalia",
    apellido: "Delgado",
    genero: "Femenino",
    telefono: "912345678",
    direccion: "Av. Santa Rosa 321",
    email: "natalia.delgado@hotmail.com",
    ciudad: "Chiclayo",
    pais: "Perú",
  },
  {
    id: 29,
    dni: "52369874",
    nombre: "César",
    apellido: "Gamarra",
    genero: "Masculino",
    telefono: "987654321",
    direccion: "Jr. Independencia 567",
    email: "cesar.gamarra@gmail.com",
    ciudad: "Lima",
    pais: "Perú",
  },
  {
    id: 30,
    dni: "25896314",
    nombre: "Valeria",
    apellido: "Pinto",
    genero: "Femenino",
    telefono: "954321876",
    direccion: "Calle Los Pinos 432",
    email: "valeria.pinto@gmail.com",
    ciudad: "Arequipa",
    pais: "Perú",
  },
];

const paginationModel = {
  rowsPerPage: "Filas por mostrar",
  page: 0,
  pageSize: 5,
};

export default function DataTable() {
  const handleEdit = (id) => {
    console.log(`Editar registro con ID: ${id}`);
  };

  const handleDelete = (id) => {
    console.log(`Eliminar registro con ID: ${id}`);
  };
  return (
    <Paper sx={{ height: "auto", width: "auto" }}>
      <h1>Lista de Clientes</h1>
      <DataGrid
        rows={rows}
        columns={columns}
        initialState={{ pagination: { paginationModel } }}
        pageSizeOptions={[5, 10]}
        checkboxSelection
        sx={{ border: 0 }}
        slotProps={{
          pagination: { labelRowsPerPage: "Filas por página" },
        }}
      />
    </Paper>
  );
}
